MvcBlogSite/Controllers/AboutController.cs
using BusinessLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogSite.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        AboutManager abm = new AboutManager();
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult Footer()
        {
            var aboutcontentlist = abm.GetAll();
            return PartialView(aboutcontentlist);
        }
        public PartialViewResult MeetTheTeam()
        {
            return PartialView();
        }
    }
}

MvcBlogSite/Controllers/AuthorController.cs
using BusinessLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogSite.Controllers
{
    public class AuthorController : Controller
    {
        // GET: Author
        BlogManager bm = new BlogManager();
        public PartialViewResult AuthorAbout(int id)
        {
            var authordetail = bm.GetBlogByID(id);
            return PartialView(authordetail);
        }
        public PartialViewResult AuthorPopularPost(int id)
        {
            var blogauthorid = bm.GetAll().Where(x => x.BlogID == id).Select(y => y.AuthorID).FirstOrDefault();
            var authorblogs = bm.GetBlogByAuthor(blogauthorid);
            return PartialView(authorblogs);
        }
    }
}

MvcBlogSite/Controllers/BlogController.cs
using BusinessLayer.Concrete;
using PagedList;
using PagedList.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogSite.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        BlogManager bm = new BlogManager();
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult BlogList(int page=1)
        {
            var bloglist = bm.GetAll().ToPagedList(page,3);
            return PartialView(bloglist);
        }
        public PartialViewResult FeaturedPosts()
        {
            // 1. post
            var posttitle1 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 1).Select(y => y.BlogTitle).FirstOrDefault();
            var postimage1 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 1).Select(y => y.BlogImage).FirstOrDefault();
            var blogdate1 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 1).Select(y => y.BlogDate).FirstOrDefault();
            ViewBag.posttitle1 = posttitle1;
            ViewBag.postimage1 = postimage1;
            ViewBag.blogdate1 = blogdate1;
            // 2. post
            var posttitle2 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 2).Select(y => y.BlogTitle).FirstOrDefault();
            var postimage2 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 2).Select(y => y.BlogImage).FirstOrDefault();
            var blogdate2 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 2).Select(y => y.BlogDate).FirstOrDefault();
            ViewBag.posttitle2 = posttitle2;
            ViewBag.postimage2 = postimage2;
            ViewBag.blogdate2 = blogdate2;
            // 3. post
            var posttitle3 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 3).Select(y => y.BlogTitle).FirstOrDefault();
            var postimage3 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 3).Select(y => y.BlogImage).FirstOrDefault();
            var blogdate3 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 3).Select(y => y.BlogDate).FirstOrDefault();
            ViewBag.posttitle3 = posttitle3;
            ViewBag.postimage3 = postimage3;
            ViewBag.blogdate3 = blogdate3;
            // 4. post
            var posttitle4 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 4).Select(y => y.BlogTitle).FirstOrDefault();
            var postimage4 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 4).Select(y => y.BlogImage).FirstOrDefault();
            var blogdate4 = bm.GetAll().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 4).Select(y => y.BlogDate).FirstOrDefault();
            ViewBag.posttitle4 = posttitle4;
            ViewBag.postimage4 = postimage4;
            ViewBag.blogdate4 = blogdate4;
            return PartialView();
            

        }
        public PartialViewResult OtherFeaturedPosts()
        {
            return PartialView();
        }
        public ActionResult BlogDetails()
        {
            return View();
        }
        public PartialViewResult BlogCover(int id)
        {
            var BlogDetailsList = bm.GetBlogByID(id);
            return PartialView(BlogDetailsList);
        }
        public PartialViewResult BlogReadAll(int id)
        {
            var BlogDetailsList = bm.GetBlogByID(id);
            return PartialView(BlogDetailsList);
        }
        public ActionResult BlogByCategory(int id)
        {
            var BlogListByCategory = bm.GetBlogByCategory(id);
            var CategoryName = bm.GetBlogByCategory(id).Select(y => y.Category.CategoryName).FirstOrDefault();
            ViewBag.CategoryName = CategoryName;
            var CategoryDesc = bm.GetBlogByCategory(id).Select(y => y.Category.CategoryDescription).FirstOrDefault();
            ViewBag.CategoryDesc = CategoryDesc;
            return View(BlogListByCategory);
        }
    }
}

MvcBlogSite/Controllers/CategoryController.cs
using BusinessLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogSite.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        CategoryManager cm = new CategoryManager();
        public ActionResult Index()
        {
            var categoryvalues = cm.GetAll();
            return View(categoryvalues);
        }
        public PartialViewResult BlogDetailsCategoryList()
        {
            var categoryvalues = cm.GetAll();
            return PartialView(categoryvalues);
        }
    }
}

MvcBlogSite/Controllers/CommentController.cs
using BusinessLayer.Concrete;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogSite.Controllers
{
    public class CommentController : Controller
    {
        // GET: Comment
        CommentManager cm = new CommentManager();
        public PartialViewResult CommentList(int id)
        {
            var commentlist = cm.CommentByBlog(id);
            return PartialView(commentlist);
        }
        [HttpGet]
        public PartialViewResult LeaveComment(int id)
        {
            ViewBag.id = id;
            return PartialView();
        }
        [HttpPost]
        public PartialViewResult LeaveComment(Comment c)
        {
            cm.CommentAdd(c);
            return PartialView();
        }
    }
}

MvcBlogSite/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogSite.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }
    }
}

MvcBlogSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogSite.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MvcBlogSite/Controllers/MailSubscribeController.cs
using BusinessLayer.Concrete;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogSite.Controllers
{
    public class MailSubscribeController : Controller
    {
        [HttpGet]
        public PartialViewResult AddMail()
        {
            return PartialView();
        }
        [HttpPost]
        public PartialViewResult AddMail(SubscribeMail p)
        {
            SubscribeMailManager sm = new SubscribeMailManager();
            sm.BLAdd(p);
            return PartialView();
        }
    }
}

MvcBlogSite/Views/About/Footer.cshtml
@model IEnumerable<EntityLayer.Concrete.About>

<div class="site-footer">
    <div class="container">
        <div class="row mb-5">
            @foreach (var x in Model)
            {
            <div class="col-md-4">
                <h3 class="footer-heading mb-4">About Us</h3>
                <p>@x.AboutContent1</p>
            </div>
            }
            <div class="col-md-3 ml-auto">
                <!-- <h3 class="footer-heading mb-4">Navigation</h3> -->
                <ul class="list-unstyled float-left mr-5">
                    <li><a href="/About/Index/">Hakkımızda</a></li>
                    <li><a href="/Contact/Index/">İletişim</a></li>
                    <li><a href="/Blog/Index">Ana Sayfa</a></li>
                    <li><a href="/Author/Login">Yazar Girişi</a></li>
                </ul>
                <ul class="list-unstyled float-left">
                    <li><a href="/Blog/BlogByCategory/1002">Seyahat</a></li>
                    <li><a href="/Blog/BlogByCategory/1">Yazılım</a></li>
                    <li><a href="/Blog/BlogByCategory/2">Teknoloji</a></li>
                    <li><a href="/Blog/BlogByCategory/3">Film & Dizi</a></li>
                </ul>
            </div>
            <div class="col-md-4">


                <div>
                    <h3 class="footer-heading mb-4">Connect With Us</h3>
                    <p>
                        <a href="#"><span class="icon-facebook pt-2 pr-2 pb-2 pl-0"></span></a>
                        <a href="#"><span class="icon-twitter p-2"></span></a>
                        <a href="#"><span class="icon-instagram p-2"></span></a>
                        <a href="#"><span class="icon-rss p-2"></span></a>
                        <a href="#"><span class="icon-envelope p-2"></span></a>
                    </p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 text-center">
                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</div>

MvcBlogSite/Views/About/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url('/miniblog/images/img_4.jpg');">
    <div class="container">
        <div class="row same-height justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="post-entry text-center">
                    <h1 class="">About Us</h1>
                    <p class="lead mb-4 text-white">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem, adipisci?</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-6 order-md-2">
                <img src="/miniblog/images/img_1.jpg" alt="Image" class="img-fluid">
            </div>
            <div class="col-md-5 mr-auto order-md-1">
                <h2>We Love To Explore</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea voluptate odit corrupti vitae cupiditate explicabo, soluta quibusdam necessitatibus, provident reprehenderit, dolorem saepe non eligendi possimus autem repellendus nesciunt, est deleniti libero recusandae officiis. Voluptatibus quisquam voluptatum expedita recusandae architecto quibusdam.</p>
                <ul class="ul-check list-unstyled success">
                    <li>Onsectetur adipisicing elit</li>
                    <li>Dolorem saepe non eligendi possimus</li>
                    <li>Voluptate odit corrupti vitae</li>
                </ul>
            </div>
        </div>
    </div>
</div>
@Html.Action("MeetTheTeam", "About")
<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img src="/miniblog/images/img_1.jpg" alt="Image" class="img-fluid">
            </div>
            <div class="col-md-5 ml-auto">
                <h2>Learn From Us</h2>
                <p class="mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea voluptate odit corrupti vitae cupiditate explicabo, soluta quibusdam necessitatibus, provident reprehenderit, dolorem saepe non eligendi possimus autem repellendus nesciunt, est deleniti libero recusandae officiis. Voluptatibus quisquam voluptatum expedita recusandae architecto quibusdam.</p>

                <ul class="ul-check list-unstyled success">
                    <li>Onsectetur adipisicing elit</li>
                    <li>Dolorem saepe non eligendi possimus</li>
                    <li>Voluptate odit corrupti vitae</li>
                </ul>
            </div>
        </div>
    </div>
</div>
@*@Html.Action("MailSubscribe", "Blog")*@

@Html.Action("Footer", "About")

MvcBlogSite/Views/About/MeetTheTeam.cshtml
<div class="site-section">
    <div class="container">
        <div class="row mb-5 justify-content-center">
            <div class="col-md-5 text-center">
                <h2>Meet The Team</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus commodi blanditiis, soluta magnam atque laborum ex qui recusandae</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-lg-4 mb-5 text-center">
                <img src="images/person_1.jpg" alt="Image" class="img-fluid w-50 rounded-circle mb-4">
                <h2 class="mb-3 h5">Kate Hampton</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum neque nobis eos quam necessitatibus rerum aliquid est tempore, cupiditate iure at voluptatum dolore, voluptates. Debitis accusamus, beatae ipsam excepturi mollitia.</p>

                <p class="mt-5">
                    <a href="#" class="p-3"><span class="icon-facebook"></span></a>
                    <a href="#" class="p-3"><span class="icon-instagram"></span></a>
                    <a href="#" class="p-3"><span class="icon-twitter"></span></a>
                </p>
            </div>

            <div class="col-md-6 col-lg-4 mb-5 text-center">
                <img src="/miniblog/images/person_2.jpg" alt="Image" class="img-fluid w-50 rounded-circle mb-4">
                <h2 class="mb-3 h5">Richard Cook</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum neque nobis eos quam necessitatibus rerum aliquid est tempore, cupiditate iure at voluptatum dolore, voluptates. Debitis accusamus, beatae ipsam excepturi mollitia.</p>

                <p class="mt-5">
                    <a href="#" class="p-3"><span class="icon-facebook"></span></a>
                    <a href="#" class="p-3"><span class="icon-instagram"></span></a>
                    <a href="#" class="p-3"><span class="icon-twitter"></span></a>
                </p>
            </div>

            <div class="col-md-6 col-lg-4 mb-5 text-center">
                <img src="images/person_3.jpg" alt="Image" class="img-fluid w-50 rounded-circle mb-4">
                <h2 class="mb-3 h5">Kevin Peters</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum neque nobis eos quam necessitatibus rerum aliquid est tempore, cupiditate iure at voluptatum dolore, voluptates. Debitis accusamus, beatae ipsam excepturi mollitia.</p>

                <p class="mt-5">
                    <a href="#" class="p-3"><span class="icon-facebook"></span></a>
                    <a href="#" class="p-3"><span class="icon-instagram"></span></a>
                    <a href="#" class="p-3"><span class="icon-twitter"></span></a>
                </p>
            </div>
        </div>
    </div>
</div>

MvcBlogSite/Views/Author/AuthorAbout.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>
@foreach (var item in Model)
{
    <div class="sidebar-box">
        <div class="bio text-center">
            <img src="@item.Author.AuthorImage" alt="Image Placeholder" class="img-fluid mb-5">
            <div class="bio-body">
                <h2>@item.Author.AuthorName</h2>
                <p class="mb-4">@item.Author.AuthorAbout</p>
                <p><a href="#" class="btn btn-primary btn-sm rounded px-4 py-2">Diğer yazılarım</a></p>
            </div>
        </div>
    </div>
}

MvcBlogSite/Views/Author/AuthorPopularPost.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>
<div class="sidebar-box">
    <h3 class="heading">Yazarın Diğer Postları</h3>
    <div class="post-entry-sidebar">
        <ul>
            @foreach (var item in Model)
            {
                <li>
                    <a href="/Blog/BlogDetails/@item.BlogID">
                        <img src="@item.BlogImage" alt="Image placeholder" class="mr-4">
                        <div class="text">
                            <h4>@item.BlogTitle</h4>
                            <div class="post-meta">
                                <span class="mr-2">@(((DateTime)item.BlogDate).ToString("dd-MMM-yyyy")) </span>
                            </div>
                        </div>
                    </a>
                </li>
            }
        </ul>
    </div>
</div>

MvcBlogSite/Views/Blog/BlogByCategory.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>
@{
    ViewBag.Title = "BlogByCategory";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <span>Category</span>
                <h3>@ViewBag.CategoryName</h3>
                <p>@ViewBag.CategoryDesc</p>
            </div>
        </div>
    </div>
</div>
<div class="site-section bg-white">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-lg-4 mb-4">
                    <div class="entry2">
                        <a href="/Blog/BlogDetails/@item.BlogID"><img src="@item.BlogImage" alt="Image" class="img-fluid rounded"></a>
                        <div class="excerpt">
                            <span class="post-category text-white bg-secondary mb-3">@item.Category.CategoryName</span>

                            <h2><a href="/Blog/BlogDetails/@item.BlogID">@item.BlogTitle</a></h2>
                            <div class="post-meta align-items-center text-left clearfix">
                                <figure class="author-figure mb-0 mr-3 float-left"><img src="@item.Author.AuthorImage" alt="Image" class="img-fluid"></figure>
                                <span class="d-inline-block mt-1">By <a href="#">@item.Author.AuthorName</a></span>
                                <span>&nbsp;-&nbsp; @(((DateTime)item.BlogDate).ToString("dd-MMM-yyyy"))</span>
                            </div>

                            <p>@item.BlogContent.Substring(0, item.BlogContent.Substring(0, 200).LastIndexOf(" "))...</p>
                            <p><a href="/Blog/BlogDetails/@item.BlogID">Read More</a></p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
@Html.Action("Footer", "About")

MvcBlogSite/Views/Blog/BlogCover.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>
@foreach (var item in Model)
{



<div class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url('@item.BlogImage')">
    <div class="container">
        <div class="row same-height justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="post-entry text-center">
                    <span class="post-category text-white bg-success mb-3">@item.Category.CategoryName</span>
                    <h1 class="mb-4"><a href="#">@item.BlogTitle</a></h1>
                    <div class="post-meta align-items-center text-center">
                        <figure class="author-figure mb-0 mr-3 d-inline-block"><img src="@item.Author.AuthorImage" alt="Image" class="img-fluid"></figure>
                        <span class="d-inline-block mt-1">@item.Author.AuthorName</span>
                        <span>&nbsp;-&nbsp; @(((DateTime)item.BlogDate).ToString("dd-MMM-yyyy"))</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
}

MvcBlogSite/Views/Blog/BlogDetails.cshtml
@{
    ViewBag.Title = "BlogDetails";
    Layout = "~/Views/Shared/Layout.cshtml";
}


@Html.Action("BlogCover", "Blog")
<section class="site-section py-lg">
    <div class="container">

        <div class="row blog-entries element-animate">

            <div class="col-md-12 col-lg-8 main-content">
                @Html.Action("BlogReadAll", "Blog")

                @Html.Action("CommentList", "Comment")
            </div>
            <div class="col-md-12 col-lg-4 sidebar">
                @Html.Action("AuthorAbout", "Author")

                @Html.Action("AuthorPopularPost", "Author")

                @Html.Action("BlogDetailsCategoryList", "Category")
            </div>
        </div>
    </div>
</section>
@*@Html.Action("OtherFeaturedPosts", "Blog")*@

@Html.Action("AddMail","MailSubscribe")

@Html.Action("Footer", "About")

MvcBlogSite/Views/Blog/BlogReadAll.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>
@foreach (var item in Model)
{



<div class="post-content-body">
    <p>@item.BlogContent</p>
    <div class="row mb-5 mt-5">
        <div class="col-md-12 mb-4">
            <img src="@item.BlogImage" alt="Image placeholder" class="img-fluid rounded">
        </div>
       
    </div>
</div>
}

MvcBlogSite/Views/Blog/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@Html.Action("FeaturedPosts","Blog")

@Html.Action("BlogList","Blog")

@*@Html.Action("OtherFeaturedPosts","Blog")*@

@Html.Action("AddMail","MailSubscribe")

@Html.Action("Footer","About")

MvcBlogSite/Views/Category/BlogDetailsCategoryList.cshtml
@model IEnumerable<EntityLayer.Concrete.Category>
<div class="sidebar-box">
    <h3 class="heading">Kategoriler</h3>
    @foreach (var item in Model)
    {
        <ul class="categories">
            <li><a href="#">@item.CategoryName<span>(0)</span></a></li>

        </ul>
    }
</div>

MvcBlogSite/Views/Category/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

MvcBlogSite/Views/Comment/CommentList.cshtml
@model IEnumerable<EntityLayer.Concrete.Comment>
<div class="pt-5">
    <h3 class="mb-5">6 Comments</h3>
    <ul class="comment-list">
      @foreach (var item in Model)
      {
        <li class="comment">
            <div class="vcard">
                <img src="~/miniblog/images/person_1.jpg" alt="Image placeholder">
            </div>
            <div class="comment-body">
                <h3>@item.Username</h3>
                <div class="meta">@(((DateTime)item.CommentDate).ToString("dd-MMM-yyyy"))</div>
                <p>@item.CommentText</p>
            </div>
        </li>   
      }
    </ul>
    @Html.Action("LeaveComment","Comment")
</div>

MvcBlogSite/Views/Comment/LeaveComment.cshtml
<div class="comment-form-wrap pt-5">
    <h3 class="mb-5">Bir Yorum Yazın </h3>
    <form method="post" class="p-5 bg-light">
        <div class="form-group">
            <label for="name">Kullanıcı Adınız *</label>
            <input type="text" class="form-control" id="Username">
        </div>
        <div class="form-group">
            <label for="email">Email *</label>
            <input type="email" class="form-control" name="Mail">
        </div>
        <input type="hidden" name="CommentDate" value="@DateTime.Now.ToShortDateString()" />
        <input type="hidden" name="BlogID" value="@ViewBag.id" />
        <div class="form-group">
            <label for="message">Yorumunuz</label>
            <textarea name="CommentText" cols="30" rows="10" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <input type="submit" value="Yorum Yap" class="btn btn-primary">
        </div>

    </form>
</div>

MvcBlogSite/Views/Contact/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url('/miniblog/images/img_4.jpg');">
    <div class="container">
        <div class="row same-height justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="post-entry text-center">
                    <h1 class="">Contact Us</h1>
                    <p class="lead mb-4 text-white">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem, adipisci?</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-7 mb-5">



                <form action="#" class="p-5 bg-white">


                    <div class="row form-group">
                        <div class="col-md-6 mb-3 mb-md-0">
                            <label class="text-black" for="fname">First Name</label>
                            <input type="text" id="fname" class="form-control">
                        </div>
                        <div class="col-md-6">
                            <label class="text-black" for="lname">Last Name</label>
                            <input type="text" id="lname" class="form-control">
                        </div>
                    </div>

                    <div class="row form-group">

                        <div class="col-md-12">
                            <label class="text-black" for="email">Email</label>
                            <input type="email" id="email" class="form-control">
                        </div>
                    </div>

                    <div class="row form-group">

                        <div class="col-md-12">
                            <label class="text-black" for="subject">Subject</label>
                            <input type="subject" id="subject" class="form-control">
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col-md-12">
                            <label class="text-black" for="message">Message</label>
                            <textarea name="message" id="message" cols="30" rows="7" class="form-control" placeholder="Write your notes or questions here..."></textarea>
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col-md-12">
                            <input type="submit" value="Send Message" class="btn btn-primary py-2 px-4 text-white">
                        </div>
                    </div>


                </form>
            </div>
            <div class="col-md-5">

                <div class="p-4 mb-3 bg-white">
                    <p class="mb-0 font-weight-bold">Address</p>
                    <p class="mb-4">203 Fake St. Mountain View, San Francisco, California, USA</p>

                    <p class="mb-0 font-weight-bold">Phone</p>
                    <p class="mb-4"><a href="#">+1 232 3235 324</a></p>

                    <p class="mb-0 font-weight-bold">Email Address</p>
                    <p class="mb-0"><a href="#">youremail@domain.com</a></p>

                </div>

            </div>
        </div>
    </div>
</div>
@Html.Action("Footer","About")

MvcBlogSite/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>